trigger:
- main

pool:
  vmImage: windows-2019

steps:
 - task: DownloadSecureFile@1
   name: mySecureFile
   inputs:
    secureFile: 'deploy.auto.pkrvars.hcl'

 - task: CopyFiles@2
   inputs:
    contents: $(mySecureFile.secureFilePath)
    TargetFolder: $(Build.SourcesDirectory)

 - script: |
    packer build .

 - task: DeleteFiles@1
   inputs:
    Contents: |
     $(mySecureFile.secureFilePath)
     $(Build.SourcesDirectory)\*.pkrvars.hcl
