trigger:
- main

pool:
  vmImage: windows-2019

steps:
 - task: DownloadSecureFile@1
   name: mySecureFile
   inputs:
    secureFile: 'deploy.auto.pkrvars.hcl'

 - script: |
    packer build -var-file="$(mySecureFile.secureFilePath)" .

 - task: DeleteFiles@1
   inputs:
    Contents: |
     $(mySecureFile.secureFilePath)
