trigger:
- main

pool:
  vmImage: windows-2019

steps:
 - task: DownloadSecureFile@1
   name: mySecureFile
   inputs:
    secureFile: 'deploy.auto.pkrvars.hcl'

 - script: |
    copy $(mySecureFile.secureFilePath) $(Agent.BuildDirectory)

 - script: |
    packer build .

 - task: DeleteFiles@1
   inputs:
    Contents: |
     $(mySecureFile.secureFilePath)
     $(Agent.BuildDirectory)
